services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  postgres-admin:
    image: dpage/pgadmin4
    ports: [ "5050:80" ]
    restart: always
    depends_on: [ "postgres" ]
    environment:
      PGADMIN_DEFAULT_EMAIL: postgresadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgresadmin
    container_name: postgres-admin

volumes:
  postgres_data:

networks:
  app:
    driver: bridge
